"""
compare_ml_vs_ground_truth.py — Compare the ML model's predict_stability_map() output
against a ground-truth grid generated by run_ground_truth_grid.py.

Read-only: loads a saved ground_truth_grids/*.npz file and calls predict_stability_map()
(no training, no model files modified). Reuses the exact same system_params/resolution/
em/moon_retrograde recorded in the ground-truth grid's metadata, so the mm_grid/am_grid
constructed by predict_stability_map() are guaranteed identical to the ground-truth grid's
(both use the same formula) -- cell-by-cell comparison requires no interpolation.

Usage:
    python compare_ml_vs_ground_truth.py ground_truth_grids/Kepler_1229_b_prograde
"""

import json
import os
import sys

import numpy as np

_src = os.path.dirname(__file__)
if _src not in sys.path:
    sys.path.insert(0, _src)


def load_ground_truth(base_path: str) -> dict:
    npz = np.load(f"{base_path}.npz")
    with open(f"{base_path}.meta.json") as f:
        meta = json.load(f)
    return {
        "mm_grid": npz["mm_grid"], "am_grid": npz["am_grid"],
        "map_stable": npz["map_stable"], "map_habitable": npz["map_habitable"],
        "map_habitable_from_temp": npz["map_habitable_from_temp"], "map_both": npz["map_both"],
        "meta": meta,
    }


def confusion(gt: np.ndarray, pred: np.ndarray) -> dict:
    tp = int(np.sum(gt & pred))
    fp = int(np.sum(~gt & pred))
    fn = int(np.sum(gt & ~pred))
    tn = int(np.sum(~gt & ~pred))
    precision = tp / (tp + fp) if (tp + fp) > 0 else float("nan")
    recall    = tp / (tp + fn) if (tp + fn) > 0 else float("nan")
    f1 = (2 * precision * recall / (precision + recall)
          if (precision + recall) > 0 and not (np.isnan(precision) or np.isnan(recall)) else float("nan"))
    accuracy = (tp + tn) / gt.size
    return {"tp": tp, "fp": fp, "fn": fn, "tn": tn,
            "accuracy": accuracy, "precision": precision, "recall": recall, "f1": f1}


def main():
    if len(sys.argv) < 2:
        print("Usage: python compare_ml_vs_ground_truth.py <ground_truth_grids/base_name> [model_dir] [rnn_type]")
        sys.exit(1)
    base_path = sys.argv[1]
    model_dir = sys.argv[2] if len(sys.argv) > 2 else "models"
    rnn_type  = sys.argv[3] if len(sys.argv) > 3 else "gru"

    gt = load_ground_truth(base_path)
    meta = gt["meta"]
    print(f"Ground truth: {meta['system_params']}  t_sim={meta['t_sim']}  "
          f"retrograde={meta['moon_retrograde']}  grid={meta['mm_resolution']}x{meta['am_resolution']}  "
          f"warmup_steps={meta['warmup_steps']}  (generated in {meta['elapsed_s']:.1f}s)")

    from exomoon.ml.inference import predict_stability_map
    ml = predict_stability_map(
        system_params=meta["system_params"], t_sim=meta["t_sim"],
        moon_retrograde=meta["moon_retrograde"], em=meta["em"],
        mm_resolution=meta["mm_resolution"], am_resolution=meta["am_resolution"],
        model_dir=model_dir, rnn_type=rnn_type,
        # warmup_steps left at predict_stability_map's own default (10) -- matches
        # the ground truth's warmup_steps as long as both were generated with the
        # same value (recorded in meta and printed above for verification).
    )
    if not ml.get("ok"):
        print("ML prediction failed:", ml)
        sys.exit(1)

    mm_grid_ml = np.array(ml["mm_grid"]); am_grid_ml = np.array(ml["am_grid"])
    if not (np.allclose(mm_grid_ml, gt["mm_grid"]) and np.allclose(am_grid_ml, gt["am_grid"])):
        print("WARNING: mm_grid/am_grid mismatch between ML and ground truth -- "
              "comparison below is not cell-aligned. Check system_params/resolution match.")

    print()
    for label, gt_map, ml_map in [
        ("stable",              gt["map_stable"],             np.array(ml["map_stable"])),
        ("habitable",           gt["map_habitable"],          np.array(ml["map_habitable"])),
        ("both (valid orbit)",  gt["map_both"],                np.array(ml["map_both"])),
    ]:
        c = confusion(gt_map, ml_map)
        print(f"--- {label} ---")
        print(f"  ground truth valid: {gt_map.sum()}/{gt_map.size}   ML valid: {ml_map.sum()}/{ml_map.size}")
        print(f"  TP={c['tp']} FP={c['fp']} FN={c['fn']} TN={c['tn']}")
        print(f"  accuracy={c['accuracy']:.3f}  precision={c['precision']:.3f}  "
              f"recall={c['recall']:.3f}  f1={c['f1']:.3f}")
        print()

    # Breakdown by am_hill bin (where ML errors are expected to cluster, near the
    # stability boundary) -- same diagnostic shape used during the warmup-fix investigation.
    am_grid = gt["am_grid"]
    gt_both = gt["map_both"]; ml_both = np.array(ml["map_both"])
    print("--- 'both' errors by am_hill bin ---")
    n_bins = 5
    edges = np.linspace(am_grid.min(), am_grid.max(), n_bins + 1)
    for b in range(n_bins):
        lo, hi = edges[b], edges[b + 1]
        col_mask = (am_grid >= lo) & (am_grid <= hi if b == n_bins - 1 else am_grid < hi)
        if not col_mask.any():
            continue
        gt_sub = gt_both[:, col_mask]; ml_sub = ml_both[:, col_mask]
        mismatch = (gt_sub != ml_sub)
        print(f"  am in [{lo:.3f},{hi:.3f}): n={gt_sub.size}  mismatches={mismatch.sum()}  "
              f"({100*mismatch.sum()/gt_sub.size:.1f}%)  "
              f"gt_valid_rate={gt_sub.mean():.2%}  ml_valid_rate={ml_sub.mean():.2%}")


if __name__ == "__main__":
    main()
